# Generated by Django 5.0 on 2023-12-24 14:58

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=5)),
                ('birthday_at', django_jalali.db.models.jDateTimeField()),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('married', models.CharField(choices=[('مجرد', 'مجرد'), ('متاهل', 'متاهل')], max_length=8)),
                ('marriage_history', models.IntegerField()),
                ('children_numbers', models.IntegerField()),
                ('created_at', django_jalali.db.models.jDateTimeField()),
            ],
        ),
    ]
