# Generated by Django 5.0 on 2024-03-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'مراجعه کنندگان', 'verbose_name_plural': 'مراجعه کنندگان'},
        ),
    ]
