version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: docker.arvancloud.ir/postgres:17.4
    env_file: .env
    volumes:
       - ../volumes/counselingAPI/postgres/data/postgres:/data/postgres
    ports:
      - "9995:5432"
    restart: unless-stopped

  nginx:
    build: nginx/
    restart: always
    volumes:
      - ./uwsgi:/tmp/uwsgi/
      - ./staticfiles:/var/www/moshavereAPI/assets/:ro
    ports:
      - "9994:80"
    depends_on:
      - django

  redis:
    image: docker.arvancloud.ir/redis:7.4.2
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ../volumes/counselingAPI/redis/redis-config/redis.conf:/usr/local/etc/redis/redis.conf
      - ../volumes/counselingAPI/redis/data:/data

  django:
    build: .
    restart: always
    volumes:
      - ./uwsgi:/tmp/uwsgi/
      - ./static:/staticfiles/
      - ./:/code
#
#  django-bot:
#    build: .
#    restart: always
#    command: >
#      sh -c "python /code/manage.py bot"
#    env_file:
#      - .env
#    depends_on:
#      - django
#    volumes:
#      - ./uwsgi:/tmp/uwsgi/
#      - ./static:/staticfiles/
#      - ./:/code
