# Generated by Django 5.0 on 2024-03-04 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('prefix_question', models.TextField(default=None)),
                ('original_question', models.TextField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_answer', models.CharField(max_length=255)),
                ('next_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_answers', to='coreAPI.questions')),
                ('self_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_answers', to='coreAPI.questions')),
            ],
        ),
        migrations.DeleteModel(
            name='Advices',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
