# Generated by Django 5.0 on 2024-03-11 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreAPI', '0003_alter_questions_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='next_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_answers', to='coreAPI.questions', verbose_name='سوال بعدی این جواب'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='original_answer',
            field=models.CharField(max_length=255, verbose_name='جواب'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='self_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_answers', to='coreAPI.questions', verbose_name='سوال مربوط به این جواب'),
        ),
    ]
