# Generated by Django 5.0 on 2024-03-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreAPI', '0007_questions_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='end',
            field=models.BooleanField(blank=True, default=False, verbose_name='آیا این پاسخ نهایی ربات است؟'),
        ),
    ]
