# Generated by Django 5.0 on 2024-03-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreAPI', '0008_alter_questions_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='start',
            field=models.BooleanField(blank=True, default=False, verbose_name='آیا این اولین سوال ربات است؟'),
        ),
    ]
