# Generated by Django 5.0 on 2023-12-14 10:53

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=11)),
                ('sent_sms_at', django_jalali.db.models.jDateTimeField()),
                ('is_mobile', models.BooleanField()),
            ],
        ),
    ]
