# Generated by Django 5.0 on 2024-03-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registermodel',
            options={'verbose_name': 'ثبت نام', 'verbose_name_plural': 'ثبت نام ها'},
        ),
    ]
