# Generated by Django 5.0 on 2024-03-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerAPI', '0002_alter_registermodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره همراه'),
        ),
    ]
