# Generated by Django 5.0 on 2024-03-11 09:40

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerAPI', '0003_alter_registermodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='is_mobile',
            field=models.BooleanField(verbose_name='آیا این شماره موبایل است؟'),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='sent_sms_at',
            field=django_jalali.db.models.jDateTimeField(verbose_name='زمان فرستاده شدن پیامک'),
        ),
    ]
